apiVersion: v1

kind: Service
metadata:
  name: rollingapp-service
  labels:
    app: rollingapp

spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: rollingapp
  sessionAffinity: None